name: net_kafka_actions

on:
  push:
    branches: [ 'master' ]
    tags-ignore: [ '*' ]
  pull_request:
    branches: [ 'master' ]
    tags-ignore: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      KAFKA_BOOTSTRAP_SERVERS: 'localhost:9092'

    steps:
      - uses: actions/checkout@v3
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.36'
      - run: bash ./install_kafka.sh
      - run: kafka/bin/zookeeper-server-start.sh -daemon kafka/config/zookeeper.properties
      - run: kafka/bin/kafka-server-start.sh -daemon kafka/config/server.properties
      - run: cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
      - run: perl Makefile.PL
#     - run: cpanm -l --installdeps .
      - run: prove -lv t