name: net_kafka_actions

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.36'
      - run: cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
      - run: install_kafka.sh
      - run: kafka/bin/zookeeper-server-start.sh -daemon kafka/config/zookeeper.properties
      - run: cpanm -l --installdeps .
      - run: prove -lv t