name: net_kafka_actions

on:
  push:
    branches: [ 'master' ]
    tags-ignore: [ '*' ]
  pull_request:
    branches: [ 'master' ]
    tags-ignore: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: confluentinc/cp-zookeeper:latest
        ports:
          - "2181:2181"

      broker:
        image: confluentinc/cp-kafka:latest
        ports:
          - "9092:9092"

    env:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

      KAFKA_CFG_KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_LISTENERS: "CLIENT://:9092,INTERNAL://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "CLIENT://localhost:9092,INTERNAL://kafka:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CLIENT:PLAINTEXT,INTERNAL:PLAINTEXT"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_BOOTSTRAP_SERVERS: localhost:9092
      KAFKA_BROKER_ID: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_TEST_TOPIC: mytopic
      KAFKA_TEST_TOPIC_PARTITIONS: p0

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

    steps:
      - run: sudo apt-get install -y librdkafka-dev
      - uses: actions/checkout@v3
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: '5.36'
      - run: cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
      - run: cpanm ExtUtils::PkgConfig
      - run: cpanm AnyEvent
      - run: cpanm AnyEvent::XSPromises
      - run: perl Makefile.PL
      - run: make
      - run: make install
      - run: prove -lv t
